export const restaurants = [
  {
    strMeal: "Baked salmon with fennel & tomatoes",
    strMealThumb: "https:\/\/www.themealdb.com\/images\/media\/meals\/1548772327.jpg",
    idRestaurant: "52959",
    strRestaurant: "Seafood",
    strRestaurantThumb: "https:\/\/www.themealdb.com\/images\/category\/seafood.png",
    strTags: "Paleo,Keto,HighFat,Baking,LowCarbs",
  },
  {
    strMeal: "Cajun spiced fish tacos",
    strMealThumb: "https:\/\/www.themealdb.com\/images\/media\/meals\/uvuyxu1503067369.jpg",
    idRestaurant: "52819",
    strRestaurant: "Seafood",
    strRestaurantThumb: "https:\/\/www.themealdb.com\/images\/category\/seafood.png",
    strTags: "Spicy,Fish",
  },
  {
    strMeal: "Escovitch Fish",
    strMealThumb: "https:\/\/www.themealdb.com\/images\/media\/meals\/1520084413.jpg",
    idRestaurant: "52944",
    strRestaurant: "Seafood",
    strRestaurantThumb: "https:\/\/www.themealdb.com\/images\/category\/seafood.png",
    strTags: "Seafood,Spicy,Speciality,Easter",
  },
  {
    strMeal: "Fish fofos",
    strMealThumb: "https:\/\/www.themealdb.com\/images\/media\/meals\/a15wsa1614349126.jpg",
    idRestaurant: "53043",
    strRestaurant: "Seafood",
    strRestaurantThumb: "https:\/\/www.themealdb.com\/images\/category\/seafood.png",
    strTags: "",
  },
  {
    strMeal: "Fish pie",
    strMealThumb: "https:\/\/www.themealdb.com\/images\/media\/meals\/ysxwuq1487323065.jpg",
    idRestaurant: "52802",
    strRestaurant: "Seafood",
    strRestaurantThumb: "https:\/\/www.themealdb.com\/images\/category\/seafood.png",
    strTags: "Fish,Pie,Breakfast,Baking",
  },
  {
    strMeal: "Fish Stew with Rouille",
    strMealThumb: "https:\/\/www.themealdb.com\/images\/media\/meals\/vptqpw1511798500.jpg",
    idRestaurant: "52918",
    strRestaurant: "Seafood",
    strRestaurantThumb: "https:\/\/www.themealdb.com\/images\/category\/seafood.png",
    strTags: "Fish,Seafood,Shellfish",
  },
]
